# yaml-language-server: $schema=../../schemas/seed-schema.json
deployed:
  l1:
    # --- Core protocol ---
    - &lidoLocator "0xbE861866E2Ca8f401e2b51b2cFb36A61B0Bf6840"
    - &lido "0x04d160820C0f2E2C693D9Eb26078189D10A1a3e1"
    - &wstETH "0xDFD55388020a8CEDADCe0B177DF5EF1E11553b43"
    - &eip712StETH "0x53520A0F043Bf005009588fcbb8Ef19bd0B98BC1"
    - &stakingRouter "0xf320D34b55E89826631C2bb1b3c5b50932cCaB3C"
    - &executionLayerRewardsVault "0xA60b3AF9244D7AF1e844d714fDc0E3796CC4390d"
    - &withdrawalQueueERC721 "0xe41d78740A1009029c44E43618Fe09C8f368851F"
    - &withdrawalVault "0x79e52DbA27718B1b618FC519A8F05a1386F4A8d2"
    - &burner "0x87d699cBC410511216BC88E8c8523A8EFf41102b"
    - &minFirstAllocationStrategy "0x9b322efdB04840052f97649fD0C27B678De88DA2"
    - &accounting "0x7d7EcCE45cAc6eF043f34e8049399b4b03044F97"
    - &accountingImpl "0xE633f4758B17c004656Bf33aac5ED9F14E713246"
    - &vaultHub "0xDfA0B34F28b1b6735d2df150a99048139302a80E"
    - &operatorGrid "0xccb86588b776743CCCB6572D2a6eAFd466012191"
    - &predepositGuarantee "0x4C003D5586B32359Df5f37B42A2E717E24817Ec2"

    # --- Oracle contracts ---
    - &accountingOracle "0xaBDf9686e4fbC7eEFff91621df82457dAb300168"
    - &hashConsensusForAccountingOracle "0x9F1c37DBCb2e01537786aEB2e6b4d6106dd81234"
    - &validatorsExitBusOracle "0xaf41922d0b9677e8CF21D72a318C72a5188dd9f1"
    - &hashConsensusForValidatorsExitBusOracle "0xF1BbbB0749736cC0c39eA1a1EDAA7fD36E2924d1"
    - &oracleReportSanityChecker "0x4077619FBAdB002fDC125171c8daf6a149C71166"
    - &oracleDaemonConfig "0x2c2e8fE09a2449aB93D9eAD68f987D33189E6168"

    # --- DAO & Aragon apps ---
    - &aragon-kernel "0xf5591B4CA4De7f3e339248bbA35b0A02Ef9939c2"
    - &ldo "0x0E9Fa6947804c5573796aE211898f7a652e58d1f"
    - &aragon-voting "0xd401Bf29751aE77cF5A479b22fbAaB30cD027dD6"
    - &aragon-token-manager "0x32Ea1c8Df51BCAd93309DB159E54415951782992"
    - &aragon-finance "0x973bD4e3F387F1BBF1576c5B12101450328F067f"
    - &aragon-agent "0x2cE254Fd852d6B5023b1B2355ae96A8d752a47cf"
    - &aragon-acl "0x428d6E1C384B743b1D6bed40b3a01F5357Ec24A9"

    # --- Staking modules ---
    - &node-operators-registry "0x94bd69Be2711205F4eBAA084c34cEf29E24A8E59"
    - &simple-dvt "0x90106946d5525003385310D8e3e123cA6CFCf5Cd"

    # --- stVaults factory stack ---
    - &stakingVaultFactory "0xBf18618d1Ba07cCcA63d3D74f6a9056762Eac3cA"
    - &stakingVaultBeacon "0xAF5bf52E784361f4eBBA86f2e918fFDd6A31453A"
    - &stakingVaultImpl "0x7ade83C09A0Aa0FEA45695840067438a9dC96361"
    - &dashboardImpl "0x5667f7477325F85C1b5E324387545C5045A57E2b"

    # ------
    - &apmRegistryFactory "0xcA98541C98bCd77123eE74C4A37b8BDfd792C4b6"
    - &aragon-apm-registry "0x85C4e347Cba194Ce2237fD19865cf9EE89A6Bb43"
    - &aragon-evm-script-registry "0x49335f718631a7aA201B459B499AFfdc1d8Ca774"
    - &aragon-repo-base "0xD03e828844AA4eF31566F984Fe2A1693e7d5aF38"
    - &aragonID "0xAa3dFDDA2670A3d2A5B9cd6669ce1E4cF99258D9"
    - &callsScript "0x207474d0f0Ba51A28ce911C2e77d6c93e231E8FD"
    - &daoFactory "0xb1833a044f74d4b37d8230941eBA11368999e057"
    - &dummyEmptyContract "0x7c625913A9c1dcCeB0799c62C0D3dfd2C21dBbE9"
    - &ens "0x5A8bF7fe99a69c2b34B540eA09d4a48c6ae78C21"
    - &ensFactory "0xf04b96fcE598C75EEAF8D517D569DE812B78683E"
    - &evmScriptRegistryFactory "0x8F002279D8A3147230dc948fB892F5BC2FfEf5d5"
    - &lidoApm "0x2F78689e4534b1461F4c35C2fC65b53205f6e50f"
    - &lidoTemplate "0xEC39F7ea18BC1c1bf3C0617fb6110dfC62d1e888"
    - &miniMeTokenFactory "0x4d0E05677c1005C4C808cb5e824abE99b2b39497"
    - &pinnedBeaconProxy "0xF19E48C5Ad2F8aBB452F5A6AB9cb104E70495e08"

roles:
  - &MANAGE_CONSENSUS_CONTRACT_ROLE "0x04a0afbbd09d5ad397fc858789da4f8edd59f5ca5098d70faa490babee945c3b"
  - &MANAGE_CONSENSUS_VERSION_ROLE "0xc31b1e4b732c5173dc51d519dfa432bad95550ecc4b0f9a61c2a558a2a8e4341"
  - &SUBMIT_DATA_ROLE "0x65fa0c17458517c727737e4153dd477fa3e328cf706640b0f68b1a285c5990da"
  - &STAKING_CONTROL_ROLE "0xa42eee1333c0758ba72be38e728b6dadb32ea767de5b4ddbaea1dae85b1b051f"
  - &RESUME_ROLE "0x2fc10cc8ae19568712f7a176fb4978616a610650813c9d05326c34abb62749c7"
  - &PAUSE_ROLE "0x139c2898040ef16910dc9f44dc697df79363da767d8bc92f2e310312b816e46d"

misc:
  - &ZERO_ADDRESS "0x0000000000000000000000000000000000000000"
  - &ZERO_BYTES32 "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &REGISTRY_BASE "0x13f43DCe264695D4118Cbc8Adb8691ABaEa0562d"
  - &DEPOSIT_CONTRACT "0x00000000219ab540356cBB839Cbe05303d7705Fa"
  - &MAX_UINT256 "115792089237316195423570985008687907853269984665640564039457584007913129639935"
  - &MAX_UINT64 "18446744073709551615"
  - &accountingImpl "0xE633f4758B17c004656Bf33aac5ED9F14E713246"
  - &lidoImpl "0x9260beB3c7876443C625c92A6f57AeD4652eB2a2"
  - &aragonTokenManagerImpl "0x3cBDFd1C852Ea9B31226d3108d5948E2a21103A8"
  - &aragonVotingImpl "0xC4943D7877936c0dAa1C3E23Bb3c179D15a489B3"
  - &nodeOperatorsRegistryImpl "0x6A3b5315C13A07270E80Cee23df99adeb7469194"
  - &aragonAclImpl "0x866Ad4D7283C4dcF00A01c1884DCDa98c2F1aE0A"
  - &aragonApmRegistryImpl "0x13f43DCe264695D4118Cbc8Adb8691ABaEa0562d"
  - &aragonEvmScriptRegistryImpl "0xA75A76Ca92068c8fe1fA2665795805aA4610999E"
  - &aragonKernelImpl "0x14dDb33F1D85997Bc35546e7E8CC306F5A7B9DD1"
  - &ensSubdomainRegistrarImpl "0x5ED5661F744E11A2076865810B0d7553b74468D2"
  - &aragonIdResolver "0x3eBCA460bA62724CaE0F801210e76dBB4f3C2A1f"
  - &operatorGridImpl "0x7FC784952EE7e96e9A8C3f271712805fc439dfD7"
  - &stakingRouterImpl "0xad7a77F8eB03ac02dfb913e5A757F543CBb2F76c"
  - &validatorsExitBusOracleImpl "0x2F09B020505e833a523A87e8A7EA238C40771214"
  - &vaultHubImpl "0xd075E66A593779994dfcA9dd0A9a12aAbC2d3B65"
  - &withdrawalQueueERC721Impl "0x15D5365e4061DA45BA2aeD01ba149d40ddCB1c78"
  - &withdrawalVaultImpl "0xb37ef8776e07f40cE146b83A5C36C2185755C40D"
  - &lidoLocatorImpl "0xC293Ea75F11C0D77416D0AFdf903d88a3891d16b"
  - &accountingOracleImpl "0x380c81B8f087f29AED8920EF12b510a182C4031C"

eoa:
  - &depositSecurityModule "0xfF772cd178D04F0B4b1EFB730c5F2B9683B31611"
  - &deployer "0x26EDb7f0f223A25EE390aCCccb577F3a31edDfC5"

l1:
  rpcUrl: HOODI_REMOTE_RPC_URL # https://ethereum-hoodi-rpc.publicnode.com
  explorerHostname: api-hoodi.etherscan.io
  explorerTokenEnv: ETHERSCAN_TOKEN
