---
# yaml-language-server: $schema=./../../schemas/seed-schema.json

deployed:
  l1:
    - &tpuProxy "0xe561152e8d3f618b386ef4dd6e3fb980eb2f9e61"
    - &proxyAdmin "0xcc6DD2e2341C5b09A6f4F481670E3C39B83810C3"
    - &impl "0x03df929510a52c97bb1b3e5f33ea5d9735a50280"
    - &rbacTimelock "0x13Ac97663d19fF20fe467BFa580748505e664beB"
l1:
  rpcUrl: https://rpc-gel.inkonchain.com
  explorerHostname: explorer.inkonchain.com
  explorerTokenEnv: INK_API_KEY
