# yaml-language-server: $schema=./../../schemas/seed-schema.json

deployed:
  l1:
    - &l1NttManager "0xb948a93827d68a82F6513Ad178964Da487fe2BD9"
    - &l1WormholeTransceiver "0xA1ACC1e6edaB281Febd91E3515093F1DE81F25c0"
    - &l1AxelarTransceiver "0x723AEAD29acee7E9281C32D11eA4ed0070c41B13"
    # Stateless libraries
    # &l1TransceiverStructs "0xf0396a8077eda579f657B5E6F3c3F5e8EE81972b"
    # &l1TransceiverStructsAxelar "0xa12bc993d8144404a8c8c812816048275a066ced"
  l2:
    - &l2wstETHToken "0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C"
    - &l2NttManager "0x6981F5621691CBfE3DdD524dE71076b79F0A0278"
    - &l2WormholeTransceiver "0xbe3F7e06872E0dF6CD7FF35B7aa4Bb1446DC9986"
    - &l2AxelarTransceiver "0x723AEAD29acee7E9281C32D11eA4ed0070c41B13"
    # Stateless libraries
    # &l2TransceiverStructs "0xf0396a8077eda579f657B5E6F3c3F5e8EE81972b"
    # &l2TransceiverStructsAxelar "0x27a3daf3b243104e9b0afae6b56026a416b852c9"

l1:
  rpcUrl: https://ethereum-rpc.publicnode.com
  explorerHostname: api.etherscan.io
  explorerTokenEnv: ETHERSCAN_TOKEN
  contracts:
    l1NttManager:
      name: NttManager
      address: *l1NttManager
      proxyName: ERC1967Proxy
      implementation: "0xc6c1f091450b54af3280cfed790047431bc99bb1"
      proxyChecks: {}
      checks:
        NTT_MANAGER_VERSION: REPLACEME # 1.1.0
        chainId: REPLACEME # 2
        getCurrentInboundCapacity: REPLACEME # need to specify args
        getCurrentOutboundCapacity: REPLACEME # 30000000000000000000000
        getInboundLimitParams: REPLACEME # need to specify args
        getInboundQueuedTransfer: REPLACEME # need to specify args
        getMigratesImmutables: REPLACEME # false
        getMode: REPLACEME # 0
        getOutboundLimitParams: REPLACEME # 768000000000008,768000000000008,1736609735
        getOutboundQueuedTransfer: REPLACEME # need to specify args
        getPeer: REPLACEME # need to specify args
        getThreshold: REPLACEME # 2
        getTransceiverInfo: REPLACEME # true,true,0,true,true,1
        getTransceivers: REPLACEME # 0xA1ACC1e6edaB281Febd91E3515093F1DE81F25c0,0x723AEAD29acee7E9281C32D11eA4ed0070c41B13
        isMessageApproved: REPLACEME # need to specify args
        isMessageExecuted: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        messageAttestations: REPLACEME # need to specify args
        mode: REPLACEME # 0
        nextMessageSequence: REPLACEME # 1518
        owner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        pauser: REPLACEME # 0x73b047fe6337183A454c5217241D780a932777bD
        quoteDeliveryPrice: REPLACEME # need to specify args
        rateLimitDuration: REPLACEME # 86400
        token: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        tokenDecimals: REPLACEME # 18
        transceiverAttestedToMessage: REPLACEME # need to specify args
      implementationChecks:
        NTT_MANAGER_VERSION: REPLACEME # 1.1.0
        chainId: REPLACEME # 2
        getCurrentInboundCapacity: REPLACEME # need to specify args
        getCurrentOutboundCapacity: REPLACEME # 0
        getInboundLimitParams: REPLACEME # need to specify args
        getInboundQueuedTransfer: REPLACEME # need to specify args
        getMigratesImmutables: REPLACEME # false
        getMode: REPLACEME # 0
        getOutboundLimitParams: REPLACEME # 0,0,0
        getOutboundQueuedTransfer: REPLACEME # need to specify args
        getPeer: REPLACEME # need to specify args
        getThreshold: REPLACEME # 0
        getTransceiverInfo: REPLACEME #
        getTransceivers: REPLACEME #
        isMessageApproved: REPLACEME # need to specify args
        isMessageExecuted: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        messageAttestations: REPLACEME # need to specify args
        mode: REPLACEME # 0
        nextMessageSequence: REPLACEME # 0
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        pauser: REPLACEME # 0x0000000000000000000000000000000000000000
        quoteDeliveryPrice: REPLACEME # need to specify args
        rateLimitDuration: REPLACEME # 86400
        token: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        tokenDecimals: REPLACEME # 18
        transceiverAttestedToMessage: REPLACEME # need to specify args
    l1WormholeTransceiver:
      name: WormholeTransceiver
      address: *l1WormholeTransceiver
      proxyName: ERC1967Proxy
      implementation: "0x3ce1230f39302e62b67bbf2316558f79c25424a2"
      proxyChecks: {}
      checks:
        WORMHOLE_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        consistencyLevel: REPLACEME # 1
        encodeWormholeTransceiverInstruction: REPLACEME # need to specify args
        gasLimit: REPLACEME # 500000
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        getNttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        getTransceiverType: REPLACEME # wormhole
        getWormholePeer: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        isSpecialRelayingEnabled: REPLACEME # need to specify args
        isVAAConsumed: REPLACEME # need to specify args
        isWormholeEvmChain: REPLACEME # need to specify args
        isWormholeRelayingEnabled: REPLACEME # need to specify args
        nttManager: REPLACEME # 0xb948a93827d68a82F6513Ad178964Da487fe2BD9
        nttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        owner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        parseWormholeTransceiverInstruction: REPLACEME # need to specify args
        pauser: REPLACEME # 0x73b047fe6337183A454c5217241D780a932777bD
        quoteDeliveryPrice: REPLACEME # need to specify args
        specialRelayer: REPLACEME # 0x63BE47835c7D66c4aA5B2C688Dc6ed9771c94C74
        wormhole: REPLACEME # 0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B
        wormholeRelayer: REPLACEME # 0x27428DD2d3DD32A4D7f7C497eAaa23130d894911
      implementationChecks:
        WORMHOLE_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        consistencyLevel: REPLACEME # 1
        encodeWormholeTransceiverInstruction: REPLACEME # need to specify args
        gasLimit: REPLACEME # 500000
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        getNttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        getTransceiverType: REPLACEME # wormhole
        getWormholePeer: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        isSpecialRelayingEnabled: REPLACEME # need to specify args
        isVAAConsumed: REPLACEME # need to specify args
        isWormholeEvmChain: REPLACEME # need to specify args
        isWormholeRelayingEnabled: REPLACEME # need to specify args
        nttManager: REPLACEME # 0xb948a93827d68a82F6513Ad178964Da487fe2BD9
        nttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        parseWormholeTransceiverInstruction: REPLACEME # need to specify args
        pauser: REPLACEME # 0x0000000000000000000000000000000000000000
        quoteDeliveryPrice: REPLACEME # need to specify args
        specialRelayer: REPLACEME # 0x63BE47835c7D66c4aA5B2C688Dc6ed9771c94C74
        wormhole: REPLACEME # 0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B
        wormholeRelayer: REPLACEME # 0x27428DD2d3DD32A4D7f7C497eAaa23130d894911
    l1AxelarTransceiver:
      name: AxelarTransceiver
      address: *l1AxelarTransceiver
      proxyName: ERC1967Proxy
      implementation: "0x87fc4b27385bb4e69a40027931229d74ef4d1943"
      proxyChecks: {}
      checks:
        AXELAR_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        gasService: REPLACEME # 0x2d5d7d31F671F86C782533cc367F14109a082712
        gateway: REPLACEME # 0x4F4495243837681061C4743b74B3eEdf548D56A5
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        getNttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        getTransceiverType: REPLACEME # axelar
        isPaused: REPLACEME # false
        nttManager: REPLACEME # 0xb948a93827d68a82F6513Ad178964Da487fe2BD9
        nttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        owner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        pauser: REPLACEME # 0x73b047fe6337183A454c5217241D780a932777bD
        quoteDeliveryPrice: REPLACEME # need to specify args
      implementationChecks:
        AXELAR_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        gasService: REPLACEME # 0x2d5d7d31F671F86C782533cc367F14109a082712
        gateway: REPLACEME # 0x4F4495243837681061C4743b74B3eEdf548D56A5
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c
        getNttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        getTransceiverType: REPLACEME # axelar
        isPaused: REPLACEME # false
        nttManager: REPLACEME # 0xb948a93827d68a82F6513Ad178964Da487fe2BD9
        nttManagerToken: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        pauser: REPLACEME # 0x0000000000000000000000000000000000000000
        quoteDeliveryPrice: REPLACEME # need to specify args

l2:
  rpcUrl: https://bsc-rpc.publicnode.com
  explorerHostname: api.bscscan.com
  explorerTokenEnv: BSCSCAN_TOKEN
  contracts:
    l2wstETHToken:
      name: WstEthL2Token
      address: *l2wstETHToken
      proxyName: ERC1967Proxy
      implementation: "0x451d447776778870bdfe76d031689703aba73ee5"
      proxyChecks: {}
      checks:
        UPGRADE_INTERFACE_VERSION: REPLACEME # 5.0.0
        allowance: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        burnFrom: REPLACEME # need to specify args
        decimals: REPLACEME # 18
        minter: REPLACEME # 0x6981F5621691CBfE3DdD524dE71076b79F0A0278
        name: REPLACEME # Wrapped liquid staked Ether 2.0
        owner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        proxiableUUID: REPLACEME # view call reverted
        symbol: REPLACEME # wstETH
        totalSupply: REPLACEME # 1000058436900000000000
      implementationChecks:
        UPGRADE_INTERFACE_VERSION: REPLACEME # 5.0.0
        allowance: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        burnFrom: REPLACEME # need to specify args
        decimals: REPLACEME # 18
        minter: REPLACEME # 0x0000000000000000000000000000000000000000
        name: REPLACEME #
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        proxiableUUID: REPLACEME # 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc
        symbol: REPLACEME #
        totalSupply: REPLACEME # 0
    l2NttManager:
      name: NttManager
      address: *l2NttManager
      proxyName: ERC1967Proxy
      implementation: "0xe82c2a5846cfb6d8683d6b636719e7aa61486838"
      proxyChecks: {}
      checks:
        NTT_MANAGER_VERSION: REPLACEME # 1.1.0
        chainId: REPLACEME # 4
        getCurrentInboundCapacity: REPLACEME # need to specify args
        getCurrentOutboundCapacity: REPLACEME # 30000000000000000000000
        getInboundLimitParams: REPLACEME # need to specify args
        getInboundQueuedTransfer: REPLACEME # need to specify args
        getMigratesImmutables: REPLACEME # false
        getMode: REPLACEME # 1
        getOutboundLimitParams: REPLACEME # 768000000000008,765847590400008,1736609345
        getOutboundQueuedTransfer: REPLACEME # need to specify args
        getPeer: REPLACEME # need to specify args
        getThreshold: REPLACEME # 2
        getTransceiverInfo: REPLACEME # true,true,0,true,true,1
        getTransceivers: REPLACEME # 0xbe3F7e06872E0dF6CD7FF35B7aa4Bb1446DC9986,0x723AEAD29acee7E9281C32D11eA4ed0070c41B13
        isMessageApproved: REPLACEME # need to specify args
        isMessageExecuted: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        messageAttestations: REPLACEME # need to specify args
        mode: REPLACEME # 1
        nextMessageSequence: REPLACEME # 217
        owner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        pauser: REPLACEME # 0xC2b778fCc3FF311Cf1abBF4E53880277bfD14C8f
        quoteDeliveryPrice: REPLACEME # need to specify args
        rateLimitDuration: REPLACEME # 86400
        token: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        tokenDecimals: REPLACEME # 18
        transceiverAttestedToMessage: REPLACEME # need to specify args
      implementationChecks:
        NTT_MANAGER_VERSION: REPLACEME # 1.1.0
        chainId: REPLACEME # 4
        getCurrentInboundCapacity: REPLACEME # need to specify args
        getCurrentOutboundCapacity: REPLACEME # 0
        getInboundLimitParams: REPLACEME # need to specify args
        getInboundQueuedTransfer: REPLACEME # need to specify args
        getMigratesImmutables: REPLACEME # false
        getMode: REPLACEME # 1
        getOutboundLimitParams: REPLACEME # 0,0,0
        getOutboundQueuedTransfer: REPLACEME # need to specify args
        getPeer: REPLACEME # need to specify args
        getThreshold: REPLACEME # 0
        getTransceiverInfo: REPLACEME #
        getTransceivers: REPLACEME #
        isMessageApproved: REPLACEME # need to specify args
        isMessageExecuted: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        messageAttestations: REPLACEME # need to specify args
        mode: REPLACEME # 1
        nextMessageSequence: REPLACEME # 0
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        pauser: REPLACEME # 0x0000000000000000000000000000000000000000
        quoteDeliveryPrice: REPLACEME # need to specify args
        rateLimitDuration: REPLACEME # 86400
        token: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        tokenDecimals: REPLACEME # 18
        transceiverAttestedToMessage: REPLACEME # need to specify args
    l2WormholeTransceiver:
      name: WormholeTransceiver
      address: *l2WormholeTransceiver
      proxyName: ERC1967Proxy
      implementation: "0xb948a93827d68a82f6513ad178964da487fe2bd9"
      proxyChecks: {}
      checks:
        WORMHOLE_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        consistencyLevel: REPLACEME # 15
        encodeWormholeTransceiverInstruction: REPLACEME # need to specify args
        gasLimit: REPLACEME # 500000
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        getNttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        getTransceiverType: REPLACEME # wormhole
        getWormholePeer: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        isSpecialRelayingEnabled: REPLACEME # need to specify args
        isVAAConsumed: REPLACEME # need to specify args
        isWormholeEvmChain: REPLACEME # need to specify args
        isWormholeRelayingEnabled: REPLACEME # need to specify args
        nttManager: REPLACEME # 0x6981F5621691CBfE3DdD524dE71076b79F0A0278
        nttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        owner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        parseWormholeTransceiverInstruction: REPLACEME # need to specify args
        pauser: REPLACEME # 0xC2b778fCc3FF311Cf1abBF4E53880277bfD14C8f
        quoteDeliveryPrice: REPLACEME # need to specify args
        specialRelayer: REPLACEME # 0x63BE47835c7D66c4aA5B2C688Dc6ed9771c94C74
        wormhole: REPLACEME # 0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B
        wormholeRelayer: REPLACEME # 0x27428DD2d3DD32A4D7f7C497eAaa23130d894911
      implementationChecks:
        WORMHOLE_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        consistencyLevel: REPLACEME # 15
        encodeWormholeTransceiverInstruction: REPLACEME # need to specify args
        gasLimit: REPLACEME # 500000
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        getNttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        getTransceiverType: REPLACEME # wormhole
        getWormholePeer: REPLACEME # need to specify args
        isPaused: REPLACEME # false
        isSpecialRelayingEnabled: REPLACEME # need to specify args
        isVAAConsumed: REPLACEME # need to specify args
        isWormholeEvmChain: REPLACEME # need to specify args
        isWormholeRelayingEnabled: REPLACEME # need to specify args
        nttManager: REPLACEME # 0x6981F5621691CBfE3DdD524dE71076b79F0A0278
        nttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        parseWormholeTransceiverInstruction: REPLACEME # need to specify args
        pauser: REPLACEME # 0x0000000000000000000000000000000000000000
        quoteDeliveryPrice: REPLACEME # need to specify args
        specialRelayer: REPLACEME # 0x63BE47835c7D66c4aA5B2C688Dc6ed9771c94C74
        wormhole: REPLACEME # 0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B
        wormholeRelayer: REPLACEME # 0x27428DD2d3DD32A4D7f7C497eAaa23130d894911
    l2AxelarTransceiver:
      name: AxelarTransceiver
      address: *l2AxelarTransceiver
      proxyName: ERC1967Proxy
      implementation: "0xa1ebb6a4b856df8bf6c3aca88a9115a9ab3b2e02"
      proxyChecks: {}
      checks:
        AXELAR_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        gasService: REPLACEME # 0x2d5d7d31F671F86C782533cc367F14109a082712
        gateway: REPLACEME # 0x304acf330bbE08d1e512eefaa92F6a57871fD895
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        getNttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        getTransceiverType: REPLACEME # axelar
        isPaused: REPLACEME # false
        nttManager: REPLACEME # 0x6981F5621691CBfE3DdD524dE71076b79F0A0278
        nttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        owner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        pauser: REPLACEME # 0xC2b778fCc3FF311Cf1abBF4E53880277bfD14C8f
        quoteDeliveryPrice: REPLACEME # need to specify args
      implementationChecks:
        AXELAR_TRANSCEIVER_VERSION: REPLACEME # 1.1.0
        gasService: REPLACEME # 0x2d5d7d31F671F86C782533cc367F14109a082712
        gateway: REPLACEME # 0x304acf330bbE08d1e512eefaa92F6a57871fD895
        getMigratesImmutables: REPLACEME # false
        getNttManagerOwner: REPLACEME # 0x8E5175D17f74d1D512de59b2f5d5A5d8177A123d
        getNttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        getTransceiverType: REPLACEME # axelar
        isPaused: REPLACEME # false
        nttManager: REPLACEME # 0x6981F5621691CBfE3DdD524dE71076b79F0A0278
        nttManagerToken: REPLACEME # 0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C
        owner: REPLACEME # 0x0000000000000000000000000000000000000000
        pauser: REPLACEME # 0x0000000000000000000000000000000000000000
        quoteDeliveryPrice: REPLACEME # need to specify args
