---
# yaml-language-server: $schema=../../../schemas/seed-schema.json
# Source config for Mellow Flexible Vaults on Ethereum Mainnet
# GitHub: https://github.com/mellow-finance/flexible-vaults
# Commit: 685be8395aef17e41615cf0bfebfbfbd51c3b582

deployed:
  l1:
    # --- Vault ---
    - &vault "0x6a37725ca7f4CE81c004c955f7280d5C704a249e"

    # --- ETH Queues ---
    - &depositQueueETH "0x1db7094Ef0D994B0b62f6Cd67dB801ad194999A8"
    - &syncDepositQueueETH "0x4a1d5dd96d6AA2Ba82e748E941d4425cb117dE84"

    # --- WETH Queues ---
    - &depositQueueWETH "0x3Fc48660d02e59fBedD0a5Cc18a5580D1f8dD6A4"
    - &syncDepositQueueWETH "0x3B374Be4c02D7367a1fDDCcDbc2EAA708BB220a0"

    # --- wstETH Queues ---
    - &depositQueueWstETH "0xe39EED9A454C4918F8d0682062777cB251cd513F"
    - &syncDepositQueueWstETH "0xD39ceac8EAfc9c8dBf52319B900CA6623730d4BA"
    - &redeemQueueWstETH "0x095bFAca9f1c6F2B063Cd67C6d6bfcd0c3aaB7b4"

    # --- GG Queues ---
    - &depositQueueGG "0x411172F1E5310d03b38128F2a294F2e33c691B30"
    - &syncDepositQueueGG "0xDc6D33047F57fCb54A6944889c5A2779EAB355a2"

    # --- strETH Queues ---
    - &depositQueueStrETH "0x268ea1cc674cdaE200c4609E7b09d03Dc618E663"
    - &syncDepositQueueStrETH "0x2161D9e85C73e7753f6Be8d0D5afBEAf416A8C58"

    # --- DVstETH Queues ---
    - &depositQueueDVstETH "0x4bDd2Ea1E20acb13f2758190c92a84175107A86f"
    - &syncDepositQueueDVstETH "0x07d82e01c73494F9b7965ED12eBDbF58E1057fBb"

    # --- Managers ---
    - &oracle "0xAda1f4c24603aB2fe5aBd35BCD12370e98A20358"
    - &shareManager "0xBBFC8683C8fE8cF73777feDE7ab9574935fea0A4"
    - &feeManager "0xed4Fac879eE86F3aB0101993A3713e7cAA0488E1"
    - &riskManager "0xa2a4C4ecE27229aF51c546844AB752824Ccb557e"

    # --- Subvaults & Verifiers ---
    - &subvault0 "0xC5901C2481ca9C26398A9Da258b13717894bfebF"
    - &verifier0 "0xBc46B79d79fCac1F4232D4Da1BA31aCED0AABFE0"
    - &subvault1 "0x7F515C80fA4C1FCFF34F0329141A9C3b20468FE5"
    - &verifier1 "0xc0FC0B74923A80Af21B1E49633cAA309f432140F"

    # --- Infrastructure ---
    - &timelockController "0x363Ba8843d06BA5968f55C26aB055162eDd62189"
    - &oracleSubmitter "0xFbD83f7C531D35D99392a5A20bb5F1e75E97076e"

misc:
  # --- Addresses / Zero values ---
  - &ZERO_ADDRESS "0x0000000000000000000000000000000000000000"
  - &ZERO_BYTES32 "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &DEFAULT_ADMIN_ROLE "0x0000000000000000000000000000000000000000000000000000000000000000"

roles:
  # --- Roles: share manager ---
  - &SET_ACCOUNT_INFO_ROLE "0x58258f737b9cea9d7da81a3a12943f800a9668a2494235fec0d84cc60ad04cff"
  - &SET_FLAGS_ROLE "0x78b235a1fa2fd5e00dba7867d599bed6f088684010a7fee7b9fe05fa1082d01e"
  - &SET_WHITELIST_MERKLE_ROOT_ROLE "0xca196afb47c2d16c8388ba0ef201b98a808acb83a856576ffc57360840a5fd99"

  # --- Roles: vault ---
  - &CREATE_QUEUE_ROLE "0x6788636e7899d6d227901dc9f8c4c785401c0991724cf908dc65388af686da6f"
  - &CREATE_SUBVAULT_ROLE "0x85c2023fdfb1e93dedf5d18f9bc0e79347e071d12740ba71aeb84a4fcbdc4b79"
  - &DISCONNECT_SUBVAULT_ROLE "0xf610639f4b9b8986f875fcb4e49486da5c7aa449a6942b5013fabd061e9b9fff"
  - &PULL_LIQUIDITY_ROLE "0x68895691ff006f290ca74825ce06ed17fffab55af49f0274f49b7424f752583a"
  - &PUSH_LIQUIDITY_ROLE "0x32a781031f04cc60b32394e40124d1e87f54273bf26d0532a115a424f6a93298"
  - &RECONNECT_SUBVAULT_ROLE "0xb557d53a2e72d8333ffa3bf2f556678becb5e995b0e25b7dca354627e550c08f"
  - &REMOVE_QUEUE_ROLE "0x9a4c49d6fb9452bbfe187968075d0fac7d7202d2b7f731d8cffbce9cf66756b2"
  - &SET_HOOK_ROLE "0x627f9e4ac2dadb64d045e7e6333c09f39ed34e0e066957955d0052b46d2e83e8"
  - &SET_QUEUE_LIMIT_ROLE "0x407fc42eadf1aba68b1d4a8c3c4aa2e8b6beac7957623f3694d0ad77bfb70e06"
  - &SET_QUEUE_STATUS_ROLE "0x6618a6d92147bbcacfb2ef2375976fc4c529eeeaeb72a66048296571370c6946"

  # --- Roles: verifier ---
  - &ALLOW_CALL_ROLE "0x7e8318b807524ed75f0b7cc82d3cd61e590497e7502a54c698a969fa62dc0a2e"
  - &CALLER_ROLE "0x877766a829235d063c3ba37802a4874fcf1b575d310fbe898df17d8ebabee463"
  - &DISALLOW_CALL_ROLE "0xf3354d076b52bf34f14c15ff5c85faef55353add7b5bb69cd8ac10c4b85748cf"
  - &SET_MERKLE_ROOT_ROLE "0xfc199f685d023b44b528c5fcb9cebfe292e64340dd5729b20761da4ad1e93024"

  # --- Roles: risk manager ---
  - &ALLOW_SUBVAULT_ASSETS_ROLE "0x4a899e3e648ea55418d9c99177e5c522df621b1953c0ad7e99da3711043ba1c1"
  - &DISALLOW_SUBVAULT_ASSETS_ROLE "0x35c8c55cb15b3aef15751488f551edf793583e377f8951cf9738f035a1649ec5"
  - &MODIFY_PENDING_ASSETS_ROLE "0xcaa6b67a612f0bc4bdf15a48dde19f543e93099681b3ceaee93d630e38bcff38"
  - &MODIFY_SUBVAULT_BALANCE_ROLE "0xa7ecfd54b0ab6ce6ecc88746fe62beba4e9a103dbb00d88cfedffbc0c6069ce8"
  - &MODIFY_VAULT_BALANCE_ROLE "0x94b8a54d503c6b752e707c591f9345ae8ccc138255588e460ee15622d499fdba"
  - &SET_SUBVAULT_LIMIT_ROLE "0x253eb39d0edc77da10bbc4bcaa23c44e40e3c67ed649fbecb18a3f7c51bfbb10"
  - &SET_VAULT_LIMIT_ROLE "0x2b2a32ecca586a148d15aea321ddbb421a2a3ac6b4d56c0a9ad9de32e84cf5c4"

  # --- Roles: oracle ---
  - &ACCEPT_REPORT_ROLE "0x341f4b58682c3a888bdb3eb9a8a4452a6e847be8a380eb3d742794b4f9ac0ab3"
  - &ADD_SUPPORTED_ASSETS_ROLE "0x73c07eddbe5b5274995c8e6cbe94d644cedc04911df3baf934188d230ca7a2cd"
  - &REMOVE_SUPPORTED_ASSETS_ROLE "0x748ab7827e75e9f34387e3ded8598f06eb04cc7bb90fff07bc6dc2a748377021"
  - &SET_SECURITY_PARAMS_ROLE "0x79abe62d91dbd05fcda41b212f4c8c1f1d8be54ccddf859de3ccd1361b71fcb6"
  - &SUBMIT_REPORTS_ROLE "0xb54eea9408efadf36da92cc5ecd8af0f45d6dd90de54634bbc5a2113ddcb505d"

  # --- Roles: timelock controller ---
  - &CANCELLER_ROLE "0xfd643c72710c63c0180259aba6b2d05451e3591a24e58b62239378085726f783"
  - &EXECUTOR_ROLE "0xd8aa0f3194971a2a116679f7c2090f6939c8d4e01a2a8d7e41d55e5351469e63"
  - &PROPOSER_ROLE "0xb09aa5aeb3702cfd50b6b62bc4532604938f21248a27a1d5ca736082b6819cc1"

l1:
  rpcUrl: L1_MAINNET_RPC_URL
  explorerHostname: api.etherscan.io/v2/api
  explorerTokenEnv: ETHERSCAN_TOKEN
  chainId: 1
